//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmbiliariagestion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DptoEntities : DbContext
    {
        public DptoEntities()
            : base("name=DptoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALQUIILER> ALQUIILER { get; set; }
        public virtual DbSet<Inmobiliaria> Inmobiliaria { get; set; }
        public virtual DbSet<Inquilino> Inquilino { get; set; }
    }
}
